### ISSUE TITLE
Spring Boot 2 support

### ISSUE THREAD

**Issue by vlastimil-dolejs** [marcosbarbero/spring-boot-starter-purge-accesslog#1]
Hi,
Do you have any plans to support spring-boot 2.0?

**Comment by marcosbarbero** [comment]
@matheusgg can you follow this up?

**Comment by vlastimil-dolejs** [comment]
It was actually pretty simple, so I have made the changes in my fork.
Should I prepare a PR for this? Maybe with a 2.0.0.RELEASE version?

**Comment by mggoes** [comment]
Hi @vlastimil-dolejs I have already started to update it to add support to Spring Boot 2, anyway be free to open a PR if you want. Thank you.

**Comment by vlastimil-dolejs** [comment]
Hi @matheusgg I have opened a PR #2 for this and two more with minor improvements. Please review them. Thank you

**Comment by mggoes** [comment]
@marcosbarbero can you generate a new release?

**Comment by marcosbarbero** [comment]
will do, I created this #5 to release a new version

**Comment by marcosbarbero** [comment]
Sorry for the long delay. I pushed the new version to the maven central and it may be available later today.
